// <auto-generated />
using System;
using DiffusionNexus.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiffusionNexus.DataAccess.Migrations
{
    [DbContext(typeof(DiffusionNexusContext))]
    partial class DiffusionNexusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("DiffusionNexus.Core.Models.GitRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("InstallRequirements")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("InstallationConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstallationConfigurationId");

                    b.ToTable("GitRepository");
                });

            modelBuilder.Entity("DiffusionNexus.Core.Models.InstallationConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InstallationConfigurations");
                });

            modelBuilder.Entity("DiffusionNexus.Core.Models.ModelDownload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("InstallationConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VramProfile")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InstallationConfigurationId");

                    b.ToTable("ModelDownload");
                });

            modelBuilder.Entity("DiffusionNexus.Core.Models.ModelDownloadLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ModelDownloadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("VramProfile")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModelDownloadId");

                    b.ToTable("ModelDownloadLink");
                });

            modelBuilder.Entity("DiffusionNexus.Core.Models.GitRepository", b =>
                {
                    b.HasOne("DiffusionNexus.Core.Models.InstallationConfiguration", null)
                        .WithMany("GitRepositories")
                        .HasForeignKey("InstallationConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DiffusionNexus.Core.Models.InstallationConfiguration", b =>
                {
                    b.OwnsOne("DiffusionNexus.Core.Models.MainRepositorySettings", "Repository", b1 =>
                        {
                            b1.Property<Guid>("InstallationConfigurationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Branch")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("CommitHash")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("RepositoryUrl")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("InstallationConfigurationId");

                            b1.ToTable("InstallationConfigurations");

                            b1.WithOwner()
                                .HasForeignKey("InstallationConfigurationId");
                        });

                    b.OwnsOne("DiffusionNexus.Core.Models.PathSettings", "Paths", b1 =>
                        {
                            b1.Property<Guid>("InstallationConfigurationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("DefaultModelDownloadDirectory")
                                .HasColumnType("TEXT");

                            b1.Property<string>("LogFileName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("RootDirectory")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("InstallationConfigurationId");

                            b1.ToTable("InstallationConfigurations");

                            b1.WithOwner()
                                .HasForeignKey("InstallationConfigurationId");
                        });

                    b.OwnsOne("DiffusionNexus.Core.Models.PythonEnvironmentSettings", "Python", b1 =>
                        {
                            b1.Property<Guid>("InstallationConfigurationId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("CreateVirtualEnvironment")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("CreateVramSettings")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("InstallSageAttention")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("InstallTriton")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("InterpreterPathOverride")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("PythonVersion")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("VirtualEnvironmentName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("InstallationConfigurationId");

                            b1.ToTable("InstallationConfigurations");

                            b1.WithOwner()
                                .HasForeignKey("InstallationConfigurationId");
                        });

                    b.OwnsOne("DiffusionNexus.Core.Models.TorchSettings", "Torch", b1 =>
                        {
                            b1.Property<Guid>("InstallationConfigurationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CudaVersion")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("IndexUrl")
                                .HasColumnType("TEXT");

                            b1.Property<string>("TorchVersion")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("InstallationConfigurationId");

                            b1.ToTable("InstallationConfigurations");

                            b1.WithOwner()
                                .HasForeignKey("InstallationConfigurationId");
                        });

                    b.OwnsOne("DiffusionNexus.Core.Models.VramSettings", "Vram", b1 =>
                        {
                            b1.Property<Guid>("InstallationConfigurationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("VramProfiles")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("InstallationConfigurationId");

                            b1.ToTable("InstallationConfigurations");

                            b1.WithOwner()
                                .HasForeignKey("InstallationConfigurationId");
                        });

                    b.Navigation("Paths")
                        .IsRequired();

                    b.Navigation("Python")
                        .IsRequired();

                    b.Navigation("Repository")
                        .IsRequired();

                    b.Navigation("Torch")
                        .IsRequired();

                    b.Navigation("Vram")
                        .IsRequired();
                });

            modelBuilder.Entity("DiffusionNexus.Core.Models.ModelDownload", b =>
                {
                    b.HasOne("DiffusionNexus.Core.Models.InstallationConfiguration", null)
                        .WithMany("ModelDownloads")
                        .HasForeignKey("InstallationConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DiffusionNexus.Core.Models.ModelDownloadLink", b =>
                {
                    b.HasOne("DiffusionNexus.Core.Models.ModelDownload", null)
                        .WithMany("DownloadLinks")
                        .HasForeignKey("ModelDownloadId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DiffusionNexus.Core.Models.InstallationConfiguration", b =>
                {
                    b.Navigation("GitRepositories");

                    b.Navigation("ModelDownloads");
                });

            modelBuilder.Entity("DiffusionNexus.Core.Models.ModelDownload", b =>
                {
                    b.Navigation("DownloadLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
