name: .NET 9 Build & Test

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      # CHANGE THIS to your actual solution/project path
      - name: Restore
        run: dotnet restore "/DiffusionNexus.Installers/DiffusionNexus.Installers.sln"

      - name: Build
        run: dotnet build "/DiffusionNexus.Installers/DiffusionNexus.Installers.sln" --no-restore --configuration Release

      - name: Test
        run: dotnet test "/DiffusionNexus.Installers/DiffusionNexus.Installers.sln" --no-build --configuration Release --verbosity normal
